export const preguntas = [
    {"id":1,"T":"E","P":"Alumno, alumna","R":"ikasle|ikaslea","C":1},
    {"id":2,"T":"E","P":"Pero","R":"baina","C":1},
    {"id":3,"T":"E","P":"Pescado","R":"arrain|arrraina","C":1},
    {"id":4,"T":"E","P":"Profesor, profesora","R":"irakasle|irakaslea","C":1},
    {"id":5,"T":"E","P":"Hola","R":"kaixo","C":1},
    {"id":6,"T":"E","P":"Buenos días","R":"egun on","C":1},
    {"id":7,"T":"E","P":"Andar bien","R":"ondo ibili","C":1},
    {"id":8,"T":"E","P":"¿Qué tal?","R":"ze lan|zer moduz","C":1},
    {"id":9,"T":"E","P":"Muchas gracias","R":"eskerrik asko","C":1},
    {"id":10,"T":"E","P":"Igualmente","R":"berdin|baita zeuei ere|halan ekarri","C":1},
    {"id":11,"T":"E","P":"Saludo","R":"agur","C":1},
    {"id":12,"T":"E","P":"Adiós","R":"adio|agur","C":1},
    {"id":13,"T":"E","P":"De nada","R":"ez horregatik","C":1},
    {"id":14,"T":"E","P":"Noche","R":"gau","C":1},
    {"id":15,"T":"E","P":"Buenas noches","R":"gabon","C":1},
    {"id":16,"T":"E","P":"Hasta luego","R":"gero arte","C":1},
    {"id":17,"T":"E","P":"¡Cuánto tiempo!","R":"aspaldiko","C":1},
    {"id":18,"T":"E","P":"Fenomenal","R":"ederto|primeran","C":1},
    {"id":19,"T":"E","P":"Buenas tardes","R":"arratsalde on|arrasti on","C":1},
    {"id":20,"T":"E","P":"Buenas tardes (usado al mediodía)","R":"eguerdi on","C":1},
    {"id":21,"T":"E","P":"Hasta la vista","R":"ikusi arte","C":1},
    {"id":22,"T":"E","P":"A ti","R":"zuri","C":1},
    {"id":23,"T":"O","P":"Nor zara zu?","R":"Ni Luisma naiz","C":1},
    {"id":24,"T":"O","P":"Nongoa zara?","R":"Ni Valentziakoa naiz","C":1},
    {"id":25,"T":"O","P":"Nongoa zara?","R":"Ni Caceresekoa naiz","C":1},
    {"id":26,"T":"O","P":"Non bizi zara?","R":"Ni Usansolon bizi naiz","C":1},
    {"id":27,"T":"E","P":"Dia","R":"egun|eguna","C":2},
    {"id":28,"T":"E","P":"Lunes","R":"astelehen|astelehena","C":2},
    {"id":29,"T":"E","P":"Martes","R":"astearte|asteartea","C":2},
    {"id":30,"T":"E","P":"Miércoles","R":"asteazken|asteazkena","C":2},
    {"id":31,"T":"E","P":"Jueves","R":"ostegun|osteguna","C":2},
    {"id":32,"T":"E","P":"Viernes","R":"ostiral|ostirala","C":2},
    {"id":33,"T":"E","P":"Sábado","R":"larunbat|larunbata","C":2},
    {"id":34,"T":"E","P":"Domingo","R":"igande|igandea","C":2},
    {"id":35,"T":"E","P":"Fin de semana","R":"asteburu|asteburua","C":2},
    {"id":36,"T":"E","P":"Enero","R":"urtarril|urtarrila","C":2},
    {"id":37,"T":"E","P":"Febrero","R":"otsail|otsaila","C":2},
    {"id":38,"T":"E","P":"Marzo","R":"martxo|martxoa","C":2},
    {"id":39,"T":"E","P":"Abril","R":"apiril|apirila","C":2},
    {"id":40,"T":"E","P":"Mayo","R":"maiaitz|maiatza","C":2},
    {"id":41,"T":"E","P":"Junio","R":"ekain|ekaina","C":2},
    {"id":42,"T":"E","P":"Julio","R":"uztail|uztaila","C":2},
    {"id":43,"T":"E","P":"Agosto","R":"abuztu|abuztua","C":2},
    {"id":44,"T":"E","P":"Septiembre","R":"irail|iraila","C":2},
    {"id":45,"T":"E","P":"Octubre","R":"urri|urria","C":2},
    {"id":46,"T":"E","P":"Noviembre","R":"azaro|azaroa","C":2},
    {"id":47,"T":"E","P":"Diciembre","R":"abendu|abendua","C":2},
    {"id":48,"T":"E","P":"Mes","R":"hil|hila|hilabete|hilabetea","C":2},
    {"id":49,"T":"E","P":"Comida (En general cualquier comida del día)","R":"otordu|otordua","C":2},
    {"id":50,"T":"E","P":"Desayuno","R":"gosari|gosaria","C":2},
    {"id":51,"T":"E","P":"Almuerzo","R":"hamaiketako|hamaiketakoa","C":2},
    {"id":52,"T":"E","P":"Comida","R":"bazkari|bazkaria","C":2},
    {"id":53,"T":"E","P":"Merienda","R":"askari|askaria","C":2},
    {"id":54,"T":"E","P":"Cena","R":"afari|afaria","C":2},
    {"id":55,"T":"E","P":"Recena","R":"sorgin-afari|sorgin-afaria","C":2},
    {"id":56,"T":"E","P":"Restauradora","R":"restauradora","C":2},
    {"id":57,"T":"E","P":"Encantado, encantada (de conocerte)","R":"urte askotarako","C":2},
    {"id":58,"T":"E","P":"Bien","R":"ondo","C":2},
    {"id":59,"T":"E","P":"Muy bien","R":"oso ondo","C":2},
    {"id":60,"T":"E","P":"Más o menos","R":"ondo esan beharko|kili-kolo|tira","C":2},
    {"id":61,"T":"E","P":"Mal","R":"txarto","C":2},
    {"id":62,"T":"E","P":"Muy mal","R":"oso txarto","C":2},
    {"id":63,"T":"E","P":"Vacío","R":"huts","C":2},
    {"id":64,"T":"E","P":"Cero","R":"zero","C":2},
    {"id":65,"T":"E","P":"Uno","R":"bat","C":2},
    {"id":66,"T":"E","P":"Dos","R":"bi","C":2},
    {"id":67,"T":"E","P":"Tres","R":"hiru","C":2},
    {"id":68,"T":"E","P":"Cuatro","R":"lau","C":2},
    {"id":69,"T":"E","P":"Cinco","R":"bost","C":2},
    {"id":70,"T":"E","P":"Seis","R":"sei","C":2},
    {"id":71,"T":"E","P":"Siete","R":"zazpi","C":2},
    {"id":72,"T":"E","P":"Ocho","R":"zortzi","C":2},
    {"id":73,"T":"E","P":"Nueve","R":"bederatzi","C":2},
    {"id":74,"T":"E","P":"Diez","R":"hamar","C":2},
    {"id":75,"T":"E","P":"Once","R":"hamaika","C":2},
    {"id":76,"T":"E","P":"Diecinueve","R":"hemeretzi","C":2},
    {"id":77,"T":"E","P":"Veinte","R":"hogei","C":2},
    {"id":78,"T":"E","P":"Cuarenta","R":"berrogei","C":2},
    {"id":79,"T":"E","P":"Sesenta","R":"hirurogei","C":2},
    {"id":80,"T":"E","P":"Ochenta","R":"laurogei","C":2},
    {"id":81,"T":"E","P":"Cien","R":"ehun","C":2},
    {"id":82,"T":"E","P":"Doscientos","R":"berrehun","C":2},
    {"id":83,"T":"E","P":"Trescientos","R":"hirurehun","C":2},
    {"id":84,"T":"E","P":"Cuatrocientos","R":"laurehun","C":2},
    {"id":85,"T":"E","P":"Mil","R":"mila","C":2},
    {"id":86,"T":"E","P":"Millón","R":"milioi","C":2},
    {"id":87,"T":"E","P":"Primero, primera","R":"lehenengo","C":2},
    {"id":88,"T":"E","P":"Segundo, segunda","R":"bigarren","C":2},
    {"id":89,"T":"E","P":"Tercer, tercero, tercera","R":"hirugarren","C":2},
    {"id":90,"T":"E","P":"Cuarto, cuarta","R":"laugarren","C":2},
    {"id":91,"T":"E","P":"Quinto, quinta","R":"bostagarren","C":2},
    {"id":92,"T":"E","P":"Sexto, sexta","R":"seigarren","C":2},
    {"id":93,"T":"E","P":"Séptimo, séptima","R":"zazpigarren","C":2},
    {"id":94,"T":"E","P":"Octavo, octaba","R":"zortzigarren","C":2},
    {"id":95,"T":"E","P":"Noveno, novena","R":"bederatzigarren","C":2},
    {"id":96,"T":"E","P":"Dédicmo, décima","R":"hamargarren","C":2},
    {"id":97,"T":"E","P":"Onceavo, onceava","R":"hamaikagarren","C":2},
    {"id":98,"T":"E","P":"Decimonoveno, decimonovena","R":"hemeretzigarren","C":2},
    {"id":99,"T":"E","P":"Administrativo, administrativa","R":"administrari|administraria","C":2},
    {"id":100,"T":"E","P":"Adviento","R":"abendu|abendua","C":2},
    {"id":101,"T":"E","P":"Aprender","R":"ikasi","C":2},
    {"id":102,"T":"E","P":"Berza, col","R":"aza","C":2},
    {"id":103,"T":"E","P":"Biologo, biologa","R":"biologo|biologoa","C":2},
    {"id":104,"T":"E","P":"Cabeza","R":"buru|burua","C":2},
    {"id":105,"T":"E","P":"Cantante","R":"abeslari|abeslaria|kantari|kantaria","C":2},
    {"id":106,"T":"E","P":"Cosecha","R":"uzta","C":2},
    {"id":107,"T":"E","P":"Curso","R":"kurtso|kurtsoa","C":2},
    {"id":108,"T":"E","P":"Director, directora","R":"zuzendari|zuzendaria","C":2},
    {"id":109,"T":"E","P":"Año","R":"urte|urtea","C":2},
    {"id":110,"T":"E","P":"Lobo, loba","R":"otso|otsoa","C":2},
    {"id":111,"T":"E","P":"Último, última","R":"azken|azkena","C":2},
    {"id":112,"T":"E","P":"Época","R":"aro|aroa","C":2},
    {"id":113,"T":"E","P":"Escaso, escasa","R":"urri|urria","C":2},
    {"id":114,"T":"E","P":"Etapa","R":"etapa","C":2},
    {"id":115,"T":"E","P":"Futbolista","R":"futbolari|futbolaria","C":2},
    {"id":116,"T":"E","P":"Helecho","R":"ira","C":2},
    {"id":117,"T":"E","P":"Hostelero, hostelera","R":"tabernari|tabernaria","C":2},
    {"id":118,"T":"E","P":"Informático, informática","R":"informatiko|informatikoa","C":2},
    {"id":119,"T":"E","P":"Pintor, pintora (de paredes u objetos)","R":"margotzaile|margotzailea","C":2},
    {"id":120,"T":"E","P":"Piso","R":"pisu|pisua","C":2},
    {"id":121,"T":"E","P":"Planta","R":"solairu|solairua","C":2},
    {"id":122,"T":"E","P":"Puerta","R":"ate|atea","C":2},
    {"id":123,"T":"E","P":"Semana","R":"aste","C":2},
    {"id":124,"T":"E","P":"Bruja, brujo","R":"sorgin|sorgina","C":2},
    {"id":125,"T":"O","P":"Zer zara zu?","R":"Ni informatikoa naiz","C":2,"TR":"Nik abeslaria bulegaria nago"},
    {"id":126,"T":"O","P":"Izaro es cantante","R":"Izaro abeslaria da","C":2,"TR":"bertsolaria abestularia dago zara"},
    {"id":127,"T":"O","P":"Yo soy informático","R":"Ni informatikoa naiz","C":2,"TR":"Nik irakaslea nago da"},
    {"id":128,"T":"O","P":"Omayra es administrativa","R":"Omayra administraria da","C":2,"TR":"Bera dago administrari dira"},
    {"id":129,"T":"O","P":"Rafa es biólogo","R":"Rafa biologoa da","C":2,"TR":"Biologaria dira dago du"},
    {"id":130,"T":"O","P":"Laura es restauradora","R":"Laura restauradora da","C":2,"TR":"dira nago zara Berak"},
    {"id":131,"T":"O","P":"Tomás es pintor","R":"Tomás margotzailea da","C":2,"TR":"Hura argazkilaria marrazkilaria dago"},
    {"id":132,"T":"O","P":"Ernesto es hostelero","R":"Ernesto tabernaria da","C":2,"TR":"dira dago hura du"},
    {"id":133,"T":"O","P":"Rebeca es alumna","R":"Rebeca ikaslea da","C":2,"TR":"irakaslea dira du dago"},
    {"id":134,"T":"O","P":"Soy miren, directora","R":"Miren naiz zuzendaria","C":2,"TR":"Nik nago irakaslea da"},
    {"id":135,"T":"O","P":"Zelan?","R":"Ondo esan beharko","C":2},
    {"id":136,"T":"O","P":"21","R":"hogeita bat","C":2,"TR":"hogei bata berrogeita bi"},
    {"id":137,"T":"O","P":"35","R":"hogeita hamabost","C":2,"TR":"eta hogei bost hamar"},
    {"id":138,"T":"O","P":"47","R":"berrogeita zazpi","C":2,"TR":"hogeita irurogeita zortzi hamazazpi"},
    {"id":139,"T":"O","P":"58","R":"berrogeita hamazortzi","C":2,"TR":"hogeita laurogeita bederatzi hamazazpi"},
    {"id":140,"T":"O","P":"65","R":"hirurogeita bost","C":2,"TR":"laurogeita berrogeita hamabost hamar"},
    {"id":141,"T":"O","P":"77","R":"hirurogeita hamazazpi","C":2,"TR":"laurogeita hiruhogeita zazpi hamazortzi"},
    {"id":142,"T":"O","P":"79","R":"hirurogeita hemeretzi","C":2,"TR":"laurogeita hirugeita hemeratzi bederatzi"},
    {"id":143,"T":"O","P":"81","R":"laurogeita bat","C":2,"TR":"berrogeita hamaika hamabi lauhogeita"},
    {"id":144,"T":"O","P":"88","R":"laurogeita zortzi","C":2,"TR":"hogeita eta zazpi hamazortzi"},
    {"id":145,"T":"O","P":"93","R":"laurogeita hamahiru","C":2,"TR":"lauogeita berrogeita hiru eta"},
    {"id":146,"T":"O","P":"94","R":"laurogeita hamalau","C":2,"TR":"laurden eta hamar lau"},
    {"id":147,"T":"O","P":"105","R":"ehun eta bost","C":2,"TR":"laurogeita hogeita lau heun"},
    {"id":148,"T":"O","P":"150","R":"ehun eta berrogeita hamar","C":2,"TR":"hirurogeita hamabi heun hogeita"},
    {"id":149,"T":"O","P":"161","R":"ehun eta hirurogeita bat","C":2,"TR":"hamaika hamabat laurogeita bostehun"},
    {"id":150,"T":"O","P":"180","R":"ehun eta laurogei","C":2,"TR":"laurehun berrogei laurden hogeita"},
    {"id":151,"T":"O","P":"35.682.932","R":"hogeita hamabost milioi seiehun eta laurogeita bi mila bederatziehun eta hogeita hamabi","C":2},
    {"id":152,"T":"O","P":"132.439.175","R":"ehun eta hogeita hamabi milioi laurehun eta hogeita hemeretzi mila ehun eta hirurogeita hamabost","C":2},
    {"id":153,"T":"O","P":"369.576.899","R":"hirurehun eta hirurogeita bederatzi milioi bostehun eta hirurogeita hamasei mila zortziehun eta laurogeita hemeretzi","C":2},
    {"id":154,"T":"O","P":"625.982.359","R":"seiehun eta hogeita bost milioi bederatziehun eta laurogeita bi mila hirurogeita eta berrogeita hemeretzi","C":2},
    {"id":155,"T":"O","P":"536.854.672","R":"bostehun eta hogeita hamasei milioi zortziehun berrogeita hamalau mila seiehun eta hirurogeita hamabi","C":2},
    {"id":156,"T":"O","P":"482.526.976","R":"laurehun eta laurogeita bi milioi bostehun eta hogeita sei mila bederatziehun eta hirurogeita hamasei","C":2},
    {"id":157,"T":"O","P":"653.765.592","R":"seiehun eta berrogeita hamahiru milioi zazpiehun eta hirurogeita bost mila bostehun eta laurogeita hamabi","C":2},
    {"id":158,"T":"O","P":"Primer piso","R":"Lehenengo pisua","C":2,"TR":"teilatu bigarren batgarren pisu"},
    {"id":159,"T":"O","P":"Segunda puerta","R":"Bigarren atea","C":2,"TR":"Berrogeita ate lehioa aulkia"},
    {"id":160,"T":"O","P":"Tercer curso","R":"Hirugarren kurtsoa","C":2,"TR":"Hirurogeita klasea hirurehun bigarren"},
    {"id":161,"T":"O","P":"Cuarto año","R":"Laugarren urtea","C":2,"TR":"Laurden laurdetan laurehun eguna"},
    {"id":162,"T":"O","P":"Onceava etapa","R":"Hamaikagarren etapa","C":2,"TR":"hamaika hamabat hamagarren hamabi"},
    {"id":163,"T":"O","P":"Zenbat urte daukaz?","R":"Nik berrogeita bost urte daukat","C":2,"TR":"Ni hogeita urtea dauka"},
    {"id":164,"T":"O","P":"Nongoa zara? eta Non bizi zara?","R":"Ni Valentziakoa naiz baina Usansolon bizi naiz","C":2,"TR":"Nik Usansolo nago da"},
    {"id":165,"T":"E","P":"Albañil","R":"igeltsero|ilgeltseroa","C":3},
    {"id":166,"T":"E","P":"Bombero, Bombera","R":"suhiltzaile|suhiltzailea","C":3},
    {"id":167,"T":"E","P":"Carne","R":"okela","C":3},
    {"id":168,"T":"E","P":"Carnicero, carnicera","R":"harakin|harakina","C":3},
    {"id":169,"T":"E","P":"Chica","R":"neska","C":3},
    {"id":170,"T":"E","P":"Cocinero, cocinera","R":"sukaldari|sukaldaria","C":3},
    {"id":171,"T":"E","P":"Conductor, conductora","R":"gidari|gidaria","C":3},
    {"id":172,"T":"E","P":"Cachorro","R":"kume|kumea","C":3},
    {"id":173,"T":"E","P":"Cuarto (Fracción de algo)","R":"laurden","C":3},
    {"id":174,"T":"E","P":"Humano, humana","R":"giza","C":3},
    {"id":175,"T":"E","P":"Derecho (Legal)","R":"eskubide|eskubidea","C":3},
    {"id":176,"T":"E","P":"Dibujante, dibujanta","R":"marrazkilari|marrazkilaria","C":3},
    {"id":177,"T":"E","P":"Enfermera, enfermero","R":"erizain|erizaina","C":3},
    {"id":178,"T":"E","P":"Fotógrafo, fotógrafa","R":"argazkilari|argazkilaria","C":3},
    {"id":179,"T":"E","P":"Hombre","R":"gizon|gizona","C":3},
    {"id":180,"T":"E","P":"Medias (Tiempo)","R":"erdiak","C":3},
    {"id":181,"T":"E","P":"Médico, médica","R":"osagile|osagilea|sendagile|sendagilea","C":3},
    {"id":182,"T":"E","P":"Mentira","R":"gezurra","C":3},
    {"id":183,"T":"E","P":"Mujer","R":"emakume|emakumea","C":3},
    {"id":184,"T":"E","P":"Niño, niña","R":"ume|umea","C":3},
    {"id":185,"T":"E","P":"Oficinista","R":"idazkari|idazkaria|bulegari|bulegaria","C":3},
    {"id":186,"T":"E","P":"Panadero, panadera","R":"okin|okina","C":3},
    {"id":187,"T":"E","P":"Pastor, pastora","R":"artzain|artzaina","C":3},
    {"id":188,"T":"E","P":"Periodista","R":"kazetari|kazetaria","C":3},
    {"id":189,"T":"E","P":"Pescador, pescadora","R":"arrantzale|arrantzalea","C":3},
    {"id":190,"T":"E","P":"Policía","R":"herrizain|herrizaina","C":3},
    {"id":191,"T":"E","P":"Político, política","R":"politikari|politikaria","C":3},
    {"id":192,"T":"E","P":"Profesión","R":"ogibide|ogibidea|lanbide|lanbidea","C":3},
    {"id":193,"T":"E","P":"Sociedad","R":"gizarte|gizartea","C":3},
    {"id":194,"T":"E","P":"Verdad","R":"egia","C":3},
    {"id":195,"T":"E","P":"Zulo","R":"zulo","C":3},
    {"id":196,"T":"E","P":"Abrir","R":"ireki","C":4},
    {"id":197,"T":"E","P":"Alegrar","R":"poztu","C":4},
    {"id":198,"T":"E","P":"Alegre (Ser)","R":"alai","C":4},
    {"id":199,"T":"E","P":"Alto, alta","R":"altu|altua","C":4},
    {"id":200,"T":"E","P":"Levantar","R":"altxatu","C":4},
    {"id":201,"T":"E","P":"Amable","R":"jatorra","C":4},
    {"id":202,"T":"E","P":"Amarillo, amarilla","R":"hori|horia","C":4},
    {"id":203,"T":"E","P":"Antipático, antipática","R":"lagungaitz|lagungaitza","C":4},
    {"id":204,"T":"E","P":"Apagar","R":"itzali","C":4},
    {"id":205,"T":"E","P":"Azul","R":"urdin","C":4},
    {"id":206,"T":"E","P":"Bajar","R":"jaitsi","C":4},
    {"id":207,"T":"E","P":"Bajo, baja","R":"baxu","C":4},
    {"id":208,"T":"E","P":"Basura","R":"zarama|zabor|zaborra","C":4},
    {"id":209,"T":"E","P":"Edan","R":"beber","C":4},
    {"id":210,"T":"E","P":"Tarde (de tiempo)","R":"berandu","C":4},
    {"id":211,"T":"E","P":"Blanco, blanca","R":"zuri|zuria","C":4},
    {"id":212,"T":"E","P":"Bonito, bonita, guapo, guapa","R":"polit|polita","C":4},
    {"id":213,"T":"E","P":"Bueno, buena","R":"on|ona","C":4},
    {"id":214,"T":"E","P":"Cabezón, cabezona","R":"burugogor|burugogorra","C":4},
    {"id":215,"T":"E","P":"Calentar","R":"berotu","C":4},
    {"id":216,"T":"E","P":"Callado, callada","R":"isilik","C":4},
    {"id":217,"T":"E","P":"Calvo, calva","R":"burusoil|burusoila","C":4},
    {"id":218,"T":"E","P":"Cerrar","R":"itxi","C":4},
    {"id":219,"T":"E","P":"Coche","R":"kotxe|kotxea","C":4},
    {"id":220,"T":"E","P":"Coger","R":"hartu","C":4},
    {"id":221,"T":"E","P":"Comer","R":"jan","C":4},
    {"id":222,"T":"E","P":"Comprar","R":"erosi","C":4},
    {"id":223,"T":"E","P":"Deberes","R":"etxerako lanak","C":4},
    {"id":224,"T":"E","P":"Delgado, delgada","R":"argal|argala","C":4},
    {"id":225,"T":"E","P":"Dormilón, dormilona","R":"loti|lotia","C":4},
    {"id":226,"T":"E","P":"Encender","R":"piztu","C":4},
    {"id":227,"T":"E","P":"Enfadar","R":"haserretu","C":4},
    {"id":228,"T":"E","P":"Enfriar","R":"hoztu","C":4},
    {"id":229,"T":"E","P":"Escribir","R":"idatzi","C":4},
    {"id":230,"T":"E","P":"Escuchar","R":"entzun","C":4},
    {"id":231,"T":"E","P":"Ese, esa, eso","R":"hori","C":4},
    {"id":232,"T":"E","P":"Estar, haber","R":"egon","C":4},
    {"id":233,"T":"E","P":"Feo, fea","R":"itsusi|itusia","C":4},
    {"id":234,"T":"E","P":"Gordo, gorda","R":"lodi|lodia|potolo","C":4},
    {"id":235,"T":"E","P":"Gris","R":"gris|grisa","C":4},
    {"id":236,"T":"E","P":"Guardar","R":"gorde","C":4},
    {"id":237,"T":"E","P":"Hablar","R":"hitz egin","C":4},
    {"id":238,"T":"E","P":"Hacer","R":"egin","C":4},
    {"id":239,"T":"E","P":"Ir","R":"joan","C":4},
    {"id":240,"T":"E","P":"Leche","R":"esne|esnea","C":4},
    {"id":241,"T":"E","P":"Leer","R":"irakurri","C":4},
    {"id":242,"T":"E","P":"Limpiar","R":"garbitu","C":4},
    {"id":243,"T":"E","P":"Llorar","R":"negar egin","C":4},
    {"id":244,"T":"E","P":"Luz","R":"argi|argia","C":4},
    {"id":245,"T":"E","P":"Malo, mala","R":"txar|txarra","C":4},
    {"id":246,"T":"E","P":"Marrón","R":"marroi|marroia","C":4},
    {"id":247,"T":"E","P":"Mesa","R":"mahai|mahaia","C":4},
    {"id":248,"T":"E","P":"Meter","R":"sartu","C":4},
    {"id":249,"T":"E","P":"Miedoso, miedosa","R":"beldurti|beldurtia","C":4},
    {"id":250,"T":"E","P":"Naranja","R":"laranja","C":4},
    {"id":251,"T":"E","P":"Negro, negra","R":"beltz|beltza","C":4},
    {"id":252,"T":"E","P":"Conmigo","R":"nirekin","C":4},
    {"id":253,"T":"E","P":"Oficina","R":"bulego|bulegoa","C":4},
    {"id":254,"T":"E","P":"Precioso, preciosa","R":"eder|ederra","C":4},
    {"id":255,"T":"E","P":"Puntual","R":"puntual|puntuala","C":4},
    {"id":256,"T":"E","P":"Quieto, quieta","R":"geldi|geldia","C":4},
    {"id":257,"T":"E","P":"Quitar","R":"kendu","C":4},
    {"id":258,"T":"E","P":"Reir","R":"barre egin","C":4},
    {"id":259,"T":"E","P":"Rojo, roja","R":"gorri|gorria","C":4},
    {"id":260,"T":"E","P":"Rosa","R":"arrosa","C":4},
    {"id":261,"T":"E","P":"Sacar","R":"atera","C":4},
    {"id":262,"T":"E","P":"Salir","R":"irten","C":4},
    {"id":263,"T":"E","P":"Saludar","R":"agur egin|agurtu","C":4},
    {"id":264,"T":"E","P":"Secar","R":"lehartu","C":4},
    {"id":265,"T":"E","P":"Sopa","R":"zopa","C":4},
    {"id":266,"T":"E","P":"Subir","R":"igo","C":4},
    {"id":267,"T":"E","P":"Televisión","R":"telebista","C":4},
    {"id":268,"T":"E","P":"Tirar","R":"bota","C":4},
    {"id":269,"T":"E","P":"Tocar","R":"ukitu","C":4},
    {"id":270,"T":"E","P":"Triste","R":"triste","C":4},
    {"id":271,"T":"E","P":"Vender","R":"saldu","C":4},
    {"id":272,"T":"E","P":"Venir","R":"etorri","C":4},
    {"id":273,"T":"E","P":"Verde","R":"berde|berdea","C":4},
    {"id":274,"T":"E","P":"Vergonzoso, vergonzosa","R":"lotsati|lotsatia","C":4},
    {"id":275,"T":"E","P":"Zapatos","R":"zapatak","C":4},
    {"id":276,"T":"O","P":"Enciende la luz","R":"Piztu argia","C":4,"TR":"Ipini bota eguzkia jaitsi"},
    {"id":277,"T":"O","P":"Apaga la televisión","R":"Itzali telebista","C":4,"TR":"Ipini Itzuli telebisioa Hartu"},
    {"id":278,"T":"O","P":"Abre la puerta","R":"Ireki atea","C":4,"TR":"Leihoa artea Ipini Igo"},
    {"id":279,"T":"O","P":"Cierra la oficina","R":"Itxi bulegoa","C":4,"TR":"Sartu Heldu sukaldea solairua"},
    {"id":280,"T":"O","P":"Bebe la leche","R":"Edan esnea","C":4,"TR":"Jan ura Egon Lan"},
    {"id":281,"T":"O","P":"Come la sopa","R":"Jan zopa","C":4,"TR":"Edan Bukatu Lan Ikasi"},
    {"id":282,"T":"O","P":"Haz los deberes","R":"Egin etxerako lanak","C":4,"TR":"Egon bulegoa Hartu Ukan"},
    {"id":283,"T":"O","P":"Calienta la cena","R":"Berotu afaria","C":4,"TR":"Hoztu askaria hamaiketako Jan"},
    {"id":284,"T":"O","P":"Saca la basura","R":"Atera zarama","C":4,"TR":"Atea kaka Irten Heldu"},
    {"id":285,"T":"O","P":"Guarda los zapatos","R":"Gorde zapatak","C":4,"TR":"Jantzi Ipini ari Hartu"},
    {"id":286,"T":"O","P":"Pon la mesa","R":"Jarri mahaia","C":4,"TR":"Jesarri aulki iturria Jaitsi"},
    {"id":287,"T":"O","P":"Tira la basura","R":"Bota zarama","C":4,"TR":"Berotu Tira Irten kaka"},
    {"id":288,"T":"O","P":"Sube a casa","R":"Igo etxera","C":4,"TR":"Azpian Jaitsi Jantzi udaletxea"},
    {"id":289,"T":"O","P":"Baja a la calle","R":"Jaitsi kalera","C":4,"TR":"Igo Berotu bidea errepidea"},
    {"id":290,"T":"O","P":"Come el pan","R":"Jan ogia","C":4,"TR":"Edan Joan Izan okina"},
    {"id":291,"T":"O","P":"Estate quieto y callado","R":"Egon geldi eta isilik","C":4,"TR":"Heldu sartu posik azkarra"},
    {"id":292,"T":"O","P":"No toques eso","R":"Ez ukitu hori","C":4,"TR":"ipini zara da Heldu"},
    {"id":293,"T":"O","P":"No vengas tarde","R":"Ez etorri berandu","C":4,"TR":"Egon isilik joan bukatu"},
    {"id":294,"T":"O","P":"No te enfades conmigo","R":"Ez haserretu nirekin","C":4,"TR":"jesarri zurekin zara zaude"},
    {"id":295,"T":"O","P":"Es la casa y la casa es verde","R":"Etxea da eta etxe berdea da","C":4,"TR":"dago ez dira berde"},
    {"id":296,"T":"O","P":"Es la bicicleta y la bicicleta es rosa","R":"Bizikleta da eta bizikleta arrosa da","C":4,"TR":"dira dago daukat nago"},
    {"id":297,"T":"O","P":"Es el gato y el gato es gris","R":"Katua da eta katu grisa da","C":4,"TR":"gris urdina dira dago"},
    {"id":298,"T":"O","P":"Es el automóvil y el automóvil es amarillo","R":"Automobila da eta automobil horia da","C":4,"TR":"Hori dira dago dauka"},
    {"id":299,"T":"O","P":"Es la puerta y la puerta es azul","R":"Atea da eta ate urdina da","C":4,"TR":"Leihoa urdin dago daukat"},
    {"id":300,"T":"O","P":"Es la mesa y la mesa es negra","R":"Mahaia da eta mahai beltza da","C":4,"TR":"grisa dago aulki gorria"},
    {"id":301,"T":"O","P":"Es la silla y la silla es morada","R":"Aulkia da eta aulki morea da","C":4,"TR":"du arrosa urdina dago"},
    {"id":302,"T":"O","P":"Es el zapato y el zapato es rojo","R":"Zapata da eta zapata gorria da","C":4,"TR":"Zapatak dira gorri dago"},
    {"id":303,"T":"O","P":"Es la mochila y la mochila es naranja","R":"Motxila da eta motxil laranja da","C":4,"TR":"naranja dira du dago"},
    {"id":304,"T":"O","P":"Es la casa y la casa es pequeña","R":"Etxea da eta etxea txikia da","C":4,"TR":"Baserri handia dago txiki"},
    {"id":305,"T":"O","P":"Es la casa y la casa no es pequeña","R":"Etxea da eta etxe ez da txikia","C":4,"TR":"dira txiki handi dago"},
    {"id":306,"T":"O","P":"Es el perro y el perro es pequeño","R":"Txakurra da eta txakur txikia da","C":4,"TR":"Katua polita pixka dago"},
    {"id":307,"T":"O","P":"Es el perro y el perro es grande","R":"Txakurra da eta txakur handia da","C":4,"TR":"txikia dago dira du"},
    {"id":308,"T":"O","P":"Es la fuente y la fuente es bonita","R":"Iturria da eta iturri polita da","C":4,"TR":"Itzuli itsusia dago naiz"},
    {"id":309,"T":"O","P":"Es la fuente y la fuente es grande","R":"Iturria da eta iturri handia da","C":4,"TR":"txikia dago dut itsusi"},
    {"id":310,"T":"O","P":"Es el pato y el pato es joven","R":"Ahatea da eta ahate gaztea da","C":4,"TR":"Txori txoria zaharra dago"},
    {"id":311,"T":"O","P":"Es el pato y el pato es viejo","R":"Ahatea da eta ahate zaharra da","C":4,"TR":"txarra atea dago dira"},
    {"id":312,"T":"E","P":"Abajo (de algo, alguien)","R":"Azpian","C":5},
    {"id":313,"T":"E","P":"Al lado","R":"Ondoan","C":5},
    {"id":314,"T":"E","P":"Alrededor","R":"Inguruan","C":5},
    {"id":315,"T":"E","P":"Arriba (de algo, alguien)","R":"Gainean","C":5},
    {"id":316,"T":"E","P":"Ayuntamiento","R":"Udaletxe|Udaletxea","C":5},
    {"id":317,"T":"E","P":"Caca","R":"Kaka","C":5},
    {"id":318,"T":"E","P":"Caserío","R":"Baserri","C":5},
    {"id":319,"T":"E","P":"Centro","R":"Erdian","C":5},
    {"id":320,"T":"E","P":"Centro de salud","R":"Osasun Zentro|Anbulatorio|Osasun zentroa|Anbulatorioa","C":5},
    {"id":321,"T":"E","P":"Chico","R":"Mutil|Mutila","C":5},
    {"id":322,"T":"E","P":"Cocina","R":"Sukalde|Sukaldea","C":5},
    {"id":323,"T":"E","P":"Cubo","R":"Kubo","C":5},
    {"id":324,"T":"E","P":"Delante","R":"Aurrean","C":5},
    {"id":325,"T":"E","P":"Dentro","R":"Barruan","C":5},
    {"id":326,"T":"E","P":"Derecha","R":"Eskuman","C":5},
    {"id":327,"T":"E","P":"Detrás","R":"Atzean","C":5},
    {"id":328,"T":"E","P":"Fuego","R":"Su|Sua","C":5},
    {"id":329,"T":"E","P":"Fuera","R":"Kanporan","C":5},
    {"id":330,"T":"E","P":"Gato, gata","R":"Katu|Katua","C":5},
    {"id":331,"T":"E","P":"Gripe","R":"Gripe|Gripea","C":5},
    {"id":332,"T":"E","P":"Izquierda","R":"Eskerran","C":5},
    {"id":333,"T":"E","P":"Ladrón, ladrona","R":"Lapur|Lapurra","C":5},
    {"id":334,"T":"E","P":"Marido","R":"Senar|Senarra","C":5},
    {"id":335,"T":"E","P":"Mascarilla","R":"Musuko|Musukoa","C":5},
    {"id":336,"T":"E","P":"Medicina (Medicamento)","R":"Sendagai|Sendagaia","C":5},
    {"id":337,"T":"E","P":"Mitad","R":"Artean","C":5},
    {"id":338,"T":"E","P":"Moneda","R":"Txanpon|Txanpona","C":5},
    {"id":339,"T":"E","P":"Monte","R":"Mendi|Mendia","C":5},
    {"id":340,"T":"E","P":"Pareja","R":"Bikote|Bikotea","C":5},
    {"id":341,"T":"E","P":"Parque","R":"Parke|Parkea","C":5},
    {"id":342,"T":"E","P":"Pelota","R":"Pilota","C":5},
    {"id":343,"T":"E","P":"Pizarra","R":"Arbel|Arbela","C":5},
    {"id":344,"T":"E","P":"Prometido","R":"Senargai|Senargaia","C":5},
    {"id":345,"T":"E","P":"Semáforo","R":"Semaforo|Semaforoa","C":5},
    {"id":346,"T":"E","P":"Fuente","R":"Iturri|Iturria","C":5},
    {"id":347,"T":"O","P":"Norekin bizi zara?","R":"Senarrekin bizi naiz","C":5,"TR":"zara nago Emaztea Senarra"},
    {"id":348,"T":"O","P":"Norekin bizi zara?","R":"Aitarekin bizi naiz","C":5,"TR":"zaude nago da Aita"},
    {"id":349,"T":"O","P":"Norekin bizi zara?","R":"Arantzarekin bizi naiz","C":5,"TR":"dira nago zara ibili"},
    {"id":350,"T":"O","P":"Norekin bizi zara?","R":"Mutilagunarekin bizi naiz","C":5,"TR":"Mutil Neskarea Nolakoa nago"},
    {"id":351,"T":"O","P":"Norekin bizi zara?","R":"Senargaiarekin bizi naiz","C":5,"TR":"nago Ez Senarra dago"},
    {"id":352,"T":"O","P":"Norekin bizi zara?","R":"Neskagunarekin bizi naiz","C":5,"TR":"Lagun nago dago izan"},
    {"id":353,"T":"O","P":"Norekin bizi zara?","R":"Bikoterekin bizi naiz","C":5,"TR":"Bikotea Bikotearen nago daukat"},
    {"id":354,"T":"E","P":"¡Cuidado con la puerta!","R":"Kontuz atearekin!","C":5},
    {"id":355,"T":"E","P":"¡Cuidado con el coche!","R":"Kontuz kotxearekin!","C":5},
    {"id":356,"T":"E","P":"¡Cuidado con la bicicleta!","R":"Kontuz bizikletarekin!","C":5},
    {"id":357,"T":"E","P":"¡Cuidado con el gato!","R":"Kontuz katuarekin!","C":5},
    {"id":358,"T":"E","P":"¡Cuidado con la cabeza!","R":"Kontuz buruarekin!","C":5},
    {"id":359,"T":"E","P":"¡Cuidado con la luz!","R":"Kontuz argiarekin!","C":5},
    {"id":360,"T":"E","P":"¡Cuidado con el semáforo","R":"Kontuz semaforoarekin!","C":5},
    {"id":361,"T":"O","P":"¿Con quién vives?","R":"Norekin bizi zara?","C":5,"TR":"Nongoa Nolakoa naiz da"},
    {"id":362,"T":"E","P":"¿Dónde estás?","R":"Non zaude?","C":5},
    {"id":363,"T":"E","P":"Estoy en el euskaltegi","R":"Euskaltegian nago","C":5},
    {"id":364,"T":"E","P":"Estoy en el ambulatorio","R":"Anbulatorioan nago","C":5},
    {"id":365,"T":"E","P":"Estoy en la fuente","R":"Iturrian nago","C":5},
    {"id":366,"T":"E","P":"Estoy en el baserri","R":"Baserrian nago","C":5},
    {"id":367,"T":"E","P":"Estoy en el ayuntamiento","R":"Udaletxean nago","C":5},
    {"id":368,"T":"E","P":"Estoy en la cocina","R":"Sukaldean nago","C":5},
    {"id":360,"T":"E","P":"Estoy en el monte","R":"Mendian nago","C":5},
    {"id":370,"T":"E","P":"Estoy en el parque","R":"Parkean nago","C":5},
    {"id":371,"T":"O","P":"Euskaltegian...","R":"Kontuz irakaslearekin! Hitz egin euskaraz","C":5,"TR":"irakaslea ikaslearekin irakaslekin jaitsi"},
    {"id":372,"T":"O","P":"Osasun zentroan...","R":"Kontuz gripearekin! Ipini musukoa","C":5,"TR":"Jaitsi gripea gripearen Jan"},
    {"id":373,"T":"O","P":"Sukaldean...","R":"Kontuz suarekin! Itzali sua","C":5,"TR":"urarekin suaren Jantzi ura"},
    {"id":374,"T":"O","P":"Mendian...","R":"Kontuz otsarekin! Korrika egin","C":5,"TR":"naiz egiten naiz zara"},
    {"id":375,"T":"O","P":"Parkean...","R":"Kontuz lapurrarekin! Gorde txanponak","C":5,"TR":"Hartu Ipini lapurraren Jaitsi"},
    {"id":376,"T":"O","P":"En el euskaltegi, ¡cuidado con la profesora! Habla euskera.","R":"Euskaltegian, kontuz irakaslearekin! Hitz Egin euskaraz","C":5,"TR":"ikaslearekin irakaslekin Jan Egon"},
    {"id":377,"T":"O","P":"En el centro de salud, ¡cuidado con la gripe! Ponte mascarilla","R":"Osasun zentroan, kontuz gripearekin! Ipini musukoa","C":5,"TR":"gripea gripearen zentroa"},
    {"id":378,"T":"O","P":"En la cocina, ¡cuidado con el fuego! Apaga el fuego","R":"Sukaldean, kontuz suarekin! Itzali sua","C":5,"TR":"Sukaldarian urarekin suaren dago"},
    {"id":379,"T":"O","P":"En el monte, ¡cuidado con los lobos! Corre","R":"Mendian, kontuz otsarekin! Korrika egin","C":5,"TR":"Mendia otsak egiten ari"},
    {"id":380,"T":"O","P":"En el parque, ¡cuidado con los ladrones! Guarda las monedas","R":"Parkean, kontuz lapurrarekin! Gorde txanponak","C":5,"TR":"Parkea lapurra jaitsi hartu"},
    {"id":381,"T":"O","P":"Non dago gizona?","R":"Gizona kotxe aurrean dago","C":5,"TR":"Gizon kotxea nago da"},
    {"id":382,"T":"O","P":"Non dago gizona?","R":"Gizona kotxe barruan dago","C":5,"TR":"Gizon Mutil nago da"},
    {"id":383,"T":"O","P":"Non dago gizona?","R":"Gizona kotxe atzean dago","C":5,"TR":"Gizon kotxea nago da"},
    {"id":384,"T":"O","P":"Non dago gizona?","R":"Gizona kotxe ezkerran dago","C":5,"TR":"Gizon kotxea nago da"},
    {"id":385,"T":"O","P":"Non dago gizona?","R":"Gizona kotxe eskuman dago","C":5,"TR":"Gizon kotxea nago da"},
    {"id":386,"T":"O","P":"Non dago gizona?","R":"Gizona kotxe ondoan dago","C":5,"TR":"Gizon kotxea nago da"},
    {"id":387,"T":"O","P":"Non dago gizona?","R":"Gizona kotxe artean dago","C":5,"TR":"Gizon kotxea nago da"},
    {"id":388,"T":"O","P":"Non dago gizona?","R":"Gizona kotxe azpian dago","C":5,"TR":"Gizon kotxea nago da"},
    {"id":389,"T":"O","P":"Non dago gizona?","R":"Gizona kotxe inguruan dago","C":5,"TR":"Gizon kotxea nago da"},
    {"id":390,"T":"O","P":"Non dago gizona?","R":"Gizona kotxe gainean dago","C":5,"TR":"Gizon kotxea nago da"},
    {"id":391,"T":"O","P":"La niña está dentro de la casa","R":"Umea etxe barruan dago","C":5,"TR":"Ume etxea erdian da"},
    {"id":392,"T":"O","P":"La niña está fuera de la casa","R":"Umea etxe kanporan dago","C":5,"TR":"Ume etxea barruan da"},
    {"id":393,"T":"O","P":"La chica está delante de la pizarra","R":"Neska arbel aurrean dago","C":5,"TR":"Mutil ahate atzean da"},
    {"id":394,"T":"O","P":"La chica está detrás de la pizarra","R":"Neska arbel atzean dago","C":5,"TR":"Mutil ahate azpian da"},
    {"id":395,"T":"O","P":"La chica está encima de la mesa","R":"Neska mahai gainean dago","C":5,"TR":"Mutil aulki aurrean da"},
    {"id":396,"T":"O","P":"La chica está debajo de la mesa","R":"Neska mahai azpian dago","C":5,"TR":"Mutil aulki artean da"},
    {"id":397,"T":"O","P":"El niño está a la derecha del cubo","R":"Umea kubo eskuman dago","C":5,"TR":"Ume mahaia eskerran da"},
    {"id":398,"T":"O","P":"El niño está a la izquierda del cubo","R":"Umea kubo ezkerran dago","C":5,"TR":"Ume mahaia eskuman da"},
    {"id":399,"T":"O","P":"La pelota está encima del niño","R":"Pilota ume gainean dago","C":5,"TR":"Ohe umea aurrean da"},
    {"id":400,"T":"O","P":"La pelota está debajo del niño","R":"Pilota ume azpian dago","C":5,"TR":"Ohe umea atzean da"},
    {"id":401,"T":"O","P":"El hombre está en el centro","R":"Gizona erdian dago","C":5,"TR":"Gizon erdia da inguruan"},
    {"id":402,"T":"O","P":"El chico está en la mitad","R":"Mutil artean dago","C":5,"TR":"Mutila aurrean da artea"},
    {"id":403,"T":"E","P":"El gato está delante de la mesa","R":"Katua mahai aurrean dago","C":5,"TR":"Katu mahaia atzean da"},
    {"id":404,"T":"E","P":"El gato está encima de la mesa","R":"Katua mahai gainean dago","C":5,"TR":"Katu mahaia azpian da"},
    {"id":405,"T":"E","P":"El gato está a la izquierda de la mesa","R":"Katua mahai eskerran dago","C":5,"TR":"Katu mahaia eskuman da"},
    {"id":406,"T":"E","P":"El gato está detrás de la mesa","R":"Katua mahai atzean dago","C":5,"TR":"Katu mahaia aurrean da"},
    {"id":407,"T":"E","P":"El gato está a la derecha de la mesa","R":"Katua mahai eskuman dago","C":5,"TR":"Katu mahaia eskerran da"},
    {"id":408,"T":"E","P":"El gato está al lado de la mesa","R":"Katua mahai ondoan dago","C":5,"TR":"Katu mahaia ondoa da"},
    {"id":409,"T":"E","P":"El gato está debajo de la mesa","R":"Katua mahai azpian dago","C":5,"TR":"Katu mahaia gainean da"},
    {"id":410,"T":"E","P":"El gato está en mitad de las mesas","R":"Katua mahai artean dago","C":5,"TR":"Katu mahaia inguruan da"},
    {"id":411,"T":"E","P":"Abrir","R":"Zabaldu|Ireki","C":6},
    {"id":412,"T":"E","P":"Ambulatorio","R":"Anbulatorio|Osasun Zentroa","C":6},
    {"id":413,"T":"E","P":"Aquí (Lugar físico)","R":"Hemen","C":6},
    {"id":414,"T":"E","P":"Aquí (Lugar físico implicando desplazamiento)","R":"Hona","C":6},
    {"id":415,"T":"E","P":"Árbol (Frutal)","R":"Arbola","C":6},
    {"id":416,"T":"E","P":"Árbol (No frutal)","R":"Zuhaitz","C":6},
    {"id":417,"T":"E","P":"Ascensor","R":"Igogailu|Igogailua","C":6},
    {"id":418,"T":"E","P":"Bicicleta","R":"Txirringa|Txirrindu||Txirrindua|Bizikleta","C":6},
    {"id":419,"T":"E","P":"Caer","R":"Jausi|Erori","C":6},
    {"id":420,"T":"E","P":"Cafetera","R":"Ehogailu|Ehogailua","C":6},
    {"id":421,"T":"E","P":"Cama","R":"Ohe|Ohea","C":6},
    {"id":422,"T":"E","P":"Carretera","R":"Errepide|Errepidea","C":6},
    {"id":423,"T":"E","P":"Cazuela","R":"Kazola","C":6},
    {"id":424,"T":"E","P":"Chimenea","R":"Tximinia","C":6},
    {"id":425,"T":"E","P":"Ciclista","R":"Txirrindulari|Txirrindularia","C":6},
    {"id":426,"T":"E","P":"Cuchara","R":"Koilara","C":6},
    {"id":427,"T":"E","P":"Navaja","R":"Labana","C":6},
    {"id":428,"T":"E","P":"Cuchillo","R":"Aizto|Aiztoa","C":6},
    {"id":429,"T":"E","P":"Dar","R":"Eman","C":6},
    {"id":430,"T":"E","P":"Dormir","R":"Lo egin","C":6},
    {"id":431,"T":"E","P":"Dormitorio","R":"Logela","C":6},
    {"id":432,"T":"E","P":"Empezar","R":"Hasi","C":6},
    {"id":433,"T":"E","P":"Escalera","R":"Eskailera","C":6},
    {"id":434,"T":"E","P":"Estropajo","R":"Iduneko|Idunekoa","C":6},
    {"id":435,"T":"E","P":"Fogones","R":"Sutegi|Sutegia","C":6},
    {"id":436,"T":"E","P":"Fontanero, fontanera","R":"Iturgin|Iturgina","C":6},
    {"id":437,"T":"E","P":"Frigorífico","R":"Hozkailu|Hozkailua","C":6},
    {"id":438,"T":"E","P":"Fuente (Bandeja)","R":"Azpil|Azpila","C":6},
    {"id":439,"T":"E","P":"Grifo","R":"Txorrota","C":6},
    {"id":440,"T":"E","P":"Horno","R":"Labe|Labea","C":6},
    {"id":441,"T":"E","P":"Hospital","R":"Ospitale|Ospitalea","C":6},
    {"id":442,"T":"E","P":"Iglesia","R":"Eliza","C":6},
    {"id":443,"T":"E","P":"Insultar","R":"Isetu","C":6},
    {"id":444,"T":"E","P":"Fregadero","R":"Sukaltarri|Sukaltarria|Harraska","C":6},
    {"id":445,"T":"E","P":"Lavadora","R":"Garbigailu|Garbigailua","C":6},
    {"id":446,"T":"E","P":"Lavavajillas","R":"Plater-ikuzgailu|Plater-izkugailua","C":6},
    {"id":447,"T":"E","P":"Levantador de piedras, levantadora de piedras","R":"Harrijasotzaile|Harrijasotzailea","C":6},
    {"id":448,"T":"E","P":"Manzana","R":"Sagar|Sagarra","C":6},
    {"id":449,"T":"E","P":"Manzano","R":"Sagarrondo|Sagarrondoa","C":6},
    {"id":450,"T":"E","P":"Microondas","R":"Mikrouhinak","C":6},
    {"id":451,"T":"E","P":"Olla","R":"Lapiko|Lapikoa","C":6},
    {"id":452,"T":"E","P":"Pájaro","R":"Txori|Txoria","C":6},
    {"id":453,"T":"E","P":"Pared","R":"Horma","C":6},
    {"id":454,"T":"E","P":"Patio","R":"Patio|Patioa","C":6},
    {"id":455,"T":"E","P":"Peinar","R":"Orraztu","C":6},
    {"id":456,"T":"E","P":"Peine","R":"Orrazi|Orrazia","C":6},
    {"id":457,"T":"E","P":"Pera","R":"Madari|Madaria","C":6},
    {"id":458,"T":"E","P":"Peral","R":"Madariondo|Madariondoa","C":6},
    {"id":459,"T":"E","P":"Piso","R":"Solairu|Solairua","C":6},
    {"id":460,"T":"E","P":"Plato","R":"Plater|Platera","C":6},
    {"id":461,"T":"E","P":"Portero, portera","R":"Atezain|Atezaina","C":6},
    {"id":462,"T":"E","P":"Sala","R":"Egongela","C":6},
    {"id":463,"T":"E","P":"Sartén","R":"Zartagin|Zartagina","C":6},
    {"id":464,"T":"E","P":"Sentar","R":"Jesarri","C":6},
    {"id":465,"T":"E","P":"Silla","R":"Aulki|Aulkia","C":6},
    {"id":466,"T":"E","P":"Taza","R":"Katilu|Katilua","C":6},
    {"id":467,"T":"E","P":"Tejado","R":"Teilatu|Teilatua","C":6},
    {"id":468,"T":"E","P":"Tendero, tendera","R":"Dendari|Dendaria","C":6},
    {"id":469,"T":"E","P":"Tenedor","R":"Sardexka","C":6},
    {"id":470,"T":"E","P":"Vaso","R":"Edalontzi|Edalontzia","C":6},
    {"id":471,"T":"E","P":"Vater","R":"Komun|Komuna","C":6},
    {"id":472,"T":"E","P":"Ventana","R":"Leiho|Lehioa","C":6},
    {"id":473,"T":"E","P":"Vestido","R":"Jantzi|Jantzia|Arropa","C":6},
    {"id":474,"T":"E","P":"Vestir","R":"Jantzi","C":6},
    {"id":475,"T":"E","P":"Cuánto","R":"Zenbat","C":6}
    ]