[
{"id":1,"T":"E","P":"Alumno, alumna","R":"ikasle|ikaslea","C":1},
{"id":2,"T":"E","P":"Pero","R":"baina","C":1},
{"id":3,"T":"E","P":"Pescado","R":"arrain|arrraina","C":1},
{"id":4,"T":"E","P":"Profesor, profesora","R":"irakasle|irakaslea","C":1},
{"id":5,"T":"E","P":"Hola","R":"kaixo","C":1},
{"id":6,"T":"E","P":"Buenos días","R":"egun on","C":1},
{"id":7,"T":"E","P":"Andar bien","R":"ondo ibili","C":1},
{"id":8,"T":"E","P":"¿Qué tal?","R":"ze lan|zer moduz","C":1},
{"id":9,"T":"E","P":"Muchas gracias","R":"eskerrik asko","C":1},
{"id":10,"T":"E","P":"Igualmente","R":"berdin|baita zeuei ere|halan ekarri","C":1},
{"id":11,"T":"E","P":"Saludo","R":"agur","C":1},
{"id":12,"T":"E","P":"Adiós","R":"adio|agur","C":1},
{"id":13,"T":"E","P":"De nada","R":"ez horregatik","C":1},
{"id":14,"T":"E","P":"Noche","R":"gau","C":1},
{"id":15,"T":"E","P":"Buenas noches","R":"gabon","C":1},
{"id":16,"T":"E","P":"Hasta luego","R":"gero arte","C":1},
{"id":17,"T":"E","P":"¡Cuánto tiempo!","R":"aspaldiko","C":1},
{"id":18,"T":"E","P":"Fenomenal","R":"ederto|primeran","C":1},
{"id":19,"T":"E","P":"Buenas tardes","R":"arratsalde on|arrasti on","C":1},
{"id":20,"T":"E","P":"Buenas tardes (usado al mediodía)","R":"eguerdi on","C":1},
{"id":21,"T":"E","P":"Hasta la vista","R":"ikusi arte","C":1},
{"id":22,"T":"E","P":"A ti","R":"zuri","C":1},
{"id":23,"T":"O","P":"Nor zara zu?","R":"Ni Luisma naiz","C":1},
{"id":24,"T":"O","P":"Nongoa zara?","R":"Ni Valentziakoa naiz","C":1},
{"id":25,"T":"O","P":"Nongoa zara?","R":"Ni Caceresekoa naiz","C":1},
{"id":26,"T":"O","P":"Non bizi zara?","R":"Ni Usansolon bizi naiz","C":1},
{"id":27,"T":"E","P":"Dia","R":"egun|eguna","C":2},
{"id":28,"T":"E","P":"Lunes","R":"astelehen|astelehena","C":2},
{"id":29,"T":"E","P":"Martes","R":"astearte|asteartea","C":2},
{"id":30,"T":"E","P":"Miércoles","R":"asteazken|asteazkena","C":2},
{"id":31,"T":"E","P":"Jueves","R":"ostegun|osteguna","C":2},
{"id":32,"T":"E","P":"Viernes","R":"ostiral|ostirala","C":2},
{"id":33,"T":"E","P":"Sábado","R":"larunbat|larunbata","C":2},
{"id":34,"T":"E","P":"Domingo","R":"igande|igandea","C":2},
{"id":35,"T":"E","P":"Fin de semana","R":"asteburu|asteburua","C":2},
{"id":36,"T":"E","P":"Enero","R":"urtarril|urtarrila","C":2},
{"id":37,"T":"E","P":"Febrero","R":"otsail|otsaila","C":2},
{"id":38,"T":"E","P":"Marzo","R":"martxo|martxoa","C":2},
{"id":39,"T":"E","P":"Abril","R":"apiril|apirila","C":2},
{"id":40,"T":"E","P":"Mayo","R":"maiaitz|maiatza","C":2},
{"id":41,"T":"E","P":"Junio","R":"ekain|ekaina","C":2},
{"id":42,"T":"E","P":"Julio","R":"uztail|uztaila","C":2},
{"id":43,"T":"E","P":"Agosto","R":"abuztu|abuztua","C":2},
{"id":44,"T":"E","P":"Septiembre","R":"irail|iraila","C":2},
{"id":45,"T":"E","P":"Octubre","R":"urri|urria","C":2},
{"id":46,"T":"E","P":"Noviembre","R":"azaro|azaroa","C":2},
{"id":47,"T":"E","P":"Diciembre","R":"abendu|abendua","C":2},
{"id":48,"T":"E","P":"Mes","R":"hil|hila|hilabete|hilabetea","C":2},
{"id":49,"T":"E","P":"Comida (En general cualquier comida del día)","R":"otordu|otordua","C":2},
{"id":50,"T":"E","P":"Desayuno","R":"gosari|gosaria","C":2},
{"id":51,"T":"E","P":"Almuerzo","R":"hamaiketako|hamaiketakoa","C":2},
{"id":52,"T":"E","P":"Comida","R":"bazkari|bazkaria","C":2},
{"id":53,"T":"E","P":"Merienda","R":"askari|askaria","C":2},
{"id":54,"T":"E","P":"Cena","R":"afari|afaria","C":2},
{"id":55,"T":"E","P":"Recena","R":"sorgin-afari|sorgin-afaria","C":2},
{"id":56,"T":"E","P":"Restauradora","R":"restauradora","C":2},
{"id":57,"T":"E","P":"Encantado, encantada (de conocerte)","R":"urte askotarako","C":2},
{"id":58,"T":"E","P":"Bien","R":"ondo","C":2},
{"id":59,"T":"E","P":"Muy bien","R":"oso ondo","C":2},
{"id":60,"T":"E","P":"Más o menos","R":"ondo esan beharko|kili-kolo|tira","C":2},
{"id":61,"T":"E","P":"Mal","R":"txarto","C":2},
{"id":62,"T":"E","P":"Muy mal","R":"oso txarto","C":2},
{"id":63,"T":"E","P":"Vacío","R":"huts","C":2},
{"id":64,"T":"E","P":"Cero","R":"zero","C":2},
{"id":65,"T":"E","P":"Uno","R":"bat","C":2},
{"id":66,"T":"E","P":"Dos","R":"bi","C":2},
{"id":67,"T":"E","P":"Tres","R":"hiru","C":2},
{"id":68,"T":"E","P":"Cuatro","R":"lau","C":2},
{"id":69,"T":"E","P":"Cinco","R":"bost","C":2},
{"id":70,"T":"E","P":"Seis","R":"sei","C":2},
{"id":71,"T":"E","P":"Siete","R":"zazpi","C":2},
{"id":72,"T":"E","P":"Ocho","R":"zortzi","C":2},
{"id":73,"T":"E","P":"Nueve","R":"bederatzi","C":2},
{"id":74,"T":"E","P":"Diez","R":"hamar","C":2},
{"id":75,"T":"E","P":"Once","R":"hamaika","C":2},
{"id":76,"T":"E","P":"Diecinueve","R":"hemeretzi","C":2},
{"id":77,"T":"E","P":"Veinte","R":"hogei","C":2},
{"id":78,"T":"E","P":"Cuarenta","R":"berrogei","C":2},
{"id":79,"T":"E","P":"Sesenta","R":"hirurogei","C":2},
{"id":80,"T":"E","P":"Ochenta","R":"laurogei","C":2},
{"id":81,"T":"E","P":"Cien","R":"ehun","C":2},
{"id":82,"T":"E","P":"Doscientos","R":"berrehun","C":2},
{"id":83,"T":"E","P":"Trescientos","R":"hirurehun","C":2},
{"id":84,"T":"E","P":"Cuatrocientos","R":"laurehun","C":2},
{"id":85,"T":"E","P":"Mil","R":"mila","C":2},
{"id":86,"T":"E","P":"Millón","R":"milioi","C":2},
{"id":87,"T":"E","P":"Primero, primera","R":"lehenengo","C":2},
{"id":88,"T":"E","P":"Segundo, segunda","R":"bigarren","C":2},
{"id":89,"T":"E","P":"Tercer, tercero, tercera","R":"hirugarren","C":2},
{"id":90,"T":"E","P":"Cuarto, cuarta","R":"laugarren","C":2},
{"id":91,"T":"E","P":"Quinto, quinta","R":"bostagarren","C":2},
{"id":92,"T":"E","P":"Sexto, sexta","R":"seigarren","C":2},
{"id":93,"T":"E","P":"Séptimo, séptima","R":"zazpigarren","C":2},
{"id":94,"T":"E","P":"Octavo, octaba","R":"zortzigarren","C":2},
{"id":95,"T":"E","P":"Noveno, novena","R":"bederatzigarren","C":2},
{"id":96,"T":"E","P":"Dédicmo, décima","R":"hamargarren","C":2},
{"id":97,"T":"E","P":"Onceavo, onceava","R":"hamaikagarren","C":2},
{"id":98,"T":"E","P":"Decimonoveno, decimonovena","R":"hemeretzigarren","C":2},
{"id":99,"T":"E","P":"Administrativo, administrativa","R":"administrari|administraria","C":2},
{"id":100,"T":"E","P":"Adviento","R":"abendu|abendua","C":2},
{"id":101,"T":"E","P":"Aprender","R":"ikasi","C":2},
{"id":102,"T":"E","P":"Berza, col","R":"aza","C":2},
{"id":103,"T":"E","P":"Biologo, biologa","R":"biologo|biologoa","C":2},
{"id":104,"T":"E","P":"Cabeza","R":"buru|burua","C":2},
{"id":105,"T":"E","P":"Cantante","R":"abeslari|abeslaria|kantari|kantaria","C":2},
{"id":106,"T":"E","P":"Cosecha","R":"uzta","C":2},
{"id":107,"T":"E","P":"Curso","R":"kurtso|kurtsoa","C":2},
{"id":108,"T":"E","P":"Director, directora","R":"zuzendari|zuzendaria","C":2},
{"id":109,"T":"E","P":"Año","R":"urte|urtea","C":2},
{"id":110,"T":"E","P":"Lobo, loba","R":"otso|otsoa","C":2},
{"id":111,"T":"E","P":"Último, última","R":"azken|azkena","C":2},
{"id":112,"T":"E","P":"Época","R":"aro|aroa","C":2},
{"id":113,"T":"E","P":"Escaso, escasa","R":"urri|urria","C":2},
{"id":114,"T":"E","P":"Etapa","R":"etapa","C":2},
{"id":115,"T":"E","P":"Futbolista","R":"futbolari|futbolaria","C":2},
{"id":116,"T":"E","P":"Helecho","R":"ira","C":2},
{"id":117,"T":"E","P":"Hostelero, hostelera","R":"tabernari|tabernaria","C":2},
{"id":118,"T":"E","P":"Informático, informática","R":"informatiko|informatikoa","C":2},
{"id":119,"T":"E","P":"Pintor, pintora (de paredes u objetos)","R":"margotzaile|margotzailea","C":2},
{"id":120,"T":"E","P":"Piso","R":"pisu|pisua","C":2},
{"id":121,"T":"E","P":"Planta","R":"solairu|solairua","C":2},
{"id":122,"T":"E","P":"Puerta","R":"ate|atea","C":2},
{"id":123,"T":"E","P":"Semana","R":"aste","C":2},
{"id":124,"T":"E","P":"Bruja, brujo","R":"sorgin|sorgina","C":2},
{"id":125,"T":"O","P":"Zer zara zu?","R":"Ni informatikoa naiz","C":2},
{"id":126,"T":"O","P":"Izaro es cantante","R":"Izaro abeslaria da","C":2},
{"id":127,"T":"O","P":"Yo soy informático","R":"Ni informatikoa naiz","C":2},
{"id":128,"T":"O","P":"Omaria es administrativa","R":"Omaira administraria da","C":2},
{"id":129,"T":"O","P":"Rafa es biólogo","R":"Rafa biologoa da","C":2},
{"id":130,"T":"O","P":"Laura es restauradora","R":"Laura restauradora da","C":2},
{"id":131,"T":"O","P":"Tomás es pintor","R":"Tomás margotzailea da","C":2},
{"id":132,"T":"O","P":"Ernesto es hostelero","R":"Ernesto tabernaria da","C":2},
{"id":133,"T":"O","P":"Rebeca es alumna","R":"Rebeca ikaslea da","C":2},
{"id":134,"T":"O","P":"Soy miren, directora","R":"Miren naiz zuzendaria","C":2},
{"id":135,"T":"O","P":"Zelan?","R":"Ondo esan beharko","C":2},
{"id":136,"T":"O","P":"21","R":"hogeita bat","C":2},
{"id":137,"T":"O","P":"35","R":"hogeita hamabost","C":2},
{"id":138,"T":"O","P":"47","R":"berrogeita zazpi","C":2},
{"id":139,"T":"O","P":"58","R":"berrogeita hamazortzi","C":2},
{"id":140,"T":"O","P":"65","R":"hirurogeita bost","C":2},
{"id":141,"T":"O","P":"77","R":"hirurogeita hamazazpi","C":2},
{"id":142,"T":"O","P":"79","R":"hirurogeita hemeretzi","C":2},
{"id":143,"T":"O","P":"81","R":"laurogeita bat","C":2},
{"id":144,"T":"O","P":"88","R":"laurogeita zortzi","C":2},
{"id":145,"T":"O","P":"93","R":"laurogeita hamahiru","C":2},
{"id":146,"T":"O","P":"94","R":"laurogeita hamalau","C":2},
{"id":147,"T":"O","P":"105","R":"ehun eta bost","C":2},
{"id":148,"T":"O","P":"150","R":"ehun eta berrogeita hamar","C":2},
{"id":149,"T":"O","P":"161","R":"ehun eta hirurogeita bat","C":2},
{"id":150,"T":"O","P":"180","R":"ehun eta laurogei","C":2},
{"id":151,"T":"O","P":"35.682.932","R":"hogeita hamabost milioi seiehun eta laurogeita bi mila bederatziehun eta hogeita hamabi","C":2},
{"id":152,"T":"O","P":"132.439.175","R":"ehun eta hogeita hamabi milioi laurehun eta hogeita hemeretzi mila ehun eta hirurogeita hamabost","C":2},
{"id":153,"T":"O","P":"369.576.899","R":"hirurehun eta hirurogeita bederatzi milioi bostehun eta hirurogeita hamasei mila zortziehun eta laurogeita hemeretzi","C":2},
{"id":154,"T":"O","P":"625.982.359","R":"seiehun eta hogeita bost milioi bederatziehun eta laurogeita bi mila hirurogeita eta berrogeita hemeretzi","C":2},
{"id":155,"T":"O","P":"536.854.672","R":"bostehun eta hogeita hamasei milioi zortziehun berrogeita hamalau mila seiehun eta hirurogeita hamabi","C":2},
{"id":156,"T":"O","P":"482.526.976","R":"laurehun eta laurogeita bi milioi bostehun eta hogeita sei mila bederatziehun eta hirurogeita hamasei","C":2},
{"id":157,"T":"O","P":"653.765.592","R":"seiehun eta berrogeita hamahiru milioi zazpiehun eta hirurogeita bost mila bostehun eta laurogeita hamabi","C":2},
{"id":158,"T":"O","P":"Primer piso","R":"Lehenengo pisua","C":2},
{"id":159,"T":"O","P":"Segunda puerta","R":"Bigarren atea","C":2},
{"id":160,"T":"O","P":"Tercer curso","R":"Hirugarren kurtsoa","C":2},
{"id":161,"T":"O","P":"Cuarto año","R":"Laugarren urtea","C":2},
{"id":162,"T":"O","P":"Onceava etapa","R":"Hamaikagarren etapa","C":2},
{"id":163,"T":"O","P":"Zenbat urte daukaz?","R":"Nik berrogeita bost urte daukat","C":2},
{"id":164,"T":"O","P":"Nongoa zara? eta Non bizi zara?","R":"Ni Valentziakoa naiz baina Usansolon bizi naiz","C":2},
{"id":165,"T":"E","P":"Albañil","R":"igeltsero|ilgeltseroa","C":3},
{"id":166,"T":"E","P":"Bombero, Bombera","R":"suhiltzaile|suhiltzailea","C":3},
{"id":167,"T":"E","P":"Carne","R":"okela","C":3},
{"id":168,"T":"E","P":"Carnicero, carnicera","R":"harakin|harakina","C":3},
{"id":169,"T":"E","P":"Chica","R":"neska","C":3},
{"id":170,"T":"E","P":"Cocinero, cocinera","R":"sukaldari|sukaldaria","C":3},
{"id":171,"T":"E","P":"Conductor, conductora","R":"gidari|gidaria","C":3},
{"id":172,"T":"E","P":"Cachorro","R":"kume|kumea","C":3},
{"id":173,"T":"E","P":"Cuarto (Fracción de algo)","R":"laurden","C":3},
{"id":174,"T":"E","P":"Humano, humana","R":"giza","C":3},
{"id":175,"T":"E","P":"Derecho (Legal)","R":"eskubide|eskubidea","C":3},
{"id":176,"T":"E","P":"Dibujante, dibujanta","R":"marrazkilari|marrazkilaria","C":3},
{"id":177,"T":"E","P":"Enfermera, enfermero","R":"erizain|erizaina","C":3},
{"id":178,"T":"E","P":"Fotógrafo, fotógrafa","R":"argazkilari|argazkilaria","C":3},
{"id":179,"T":"E","P":"Hombre","R":"gizon|gizona","C":3},
{"id":180,"T":"E","P":"Medias (Tiempo)","R":"erdiak","C":3},
{"id":181,"T":"E","P":"Médico, médica","R":"osagile|osagilea|sendagile|sendagilea","C":3},
{"id":182,"T":"E","P":"Mentira","R":"gezurra","C":3},
{"id":183,"T":"E","P":"Mujer","R":"emakume|emakumea","C":3},
{"id":184,"T":"E","P":"Niño, niña","R":"ume|umea","C":3},
{"id":185,"T":"E","P":"Oficinista","R":"idazkari|idazkaria|bulegari|bulegaria","C":3},
{"id":186,"T":"E","P":"Panadero, panadera","R":"okin|okina","C":3},
{"id":187,"T":"E","P":"Pastor, pastora","R":"artzain|artzaina","C":3},
{"id":188,"T":"E","P":"Periodista","R":"kazetari|kazetaria","C":3},
{"id":189,"T":"E","P":"Pescador, pescadora","R":"arrantzale|arrantzalea","C":3},
{"id":190,"T":"E","P":"Policía","R":"herrizain|herrizaina","C":3},
{"id":191,"T":"E","P":"Político, política","R":"politikari|politikaria","C":3},
{"id":192,"T":"E","P":"Profesión","R":"ogibide|ogibidea|lanbide|lanbidea","C":3},
{"id":193,"T":"E","P":"Sociedad","R":"gizarte|gizartea","C":3},
{"id":194,"T":"E","P":"Verdad","R":"egia","C":3},
{"id":195,"T":"E","P":"Zulo","R":"zulo","C":3},
{"id":196,"T":"E","P":"Abrir","R":"ireki","C":4},
{"id":197,"T":"E","P":"Alegrar","R":"poztu","C":4},
{"id":198,"T":"E","P":"Alegre (Ser)","R":"alai","C":4},
{"id":199,"T":"E","P":"Alto, alta","R":"altu|altua","C":4},
{"id":200,"T":"E","P":"Levantar","R":"altxatu","C":4},
{"id":201,"T":"E","P":"Amable","R":"jatorra","C":4},
{"id":202,"T":"E","P":"Amarillo, amarilla","R":"hori|horia","C":4},
{"id":203,"T":"E","P":"Antipático, antipática","R":"lagungaitz|lagungaitza","C":4},
{"id":204,"T":"E","P":"Apagar","R":"itzali","C":4},
{"id":205,"T":"E","P":"Azul","R":"urdin","C":4},
{"id":206,"T":"E","P":"Bajar","R":"jaitsi","C":4},
{"id":207,"T":"E","P":"Bajo, baja","R":"baxu","C":4},
{"id":208,"T":"E","P":"Basura","R":"zarama|zabor|zaborra","C":4},
{"id":209,"T":"E","P":"Edan","R":"beber","C":4},
{"id":210,"T":"E","P":"Tarde (de tiempo)","R":"berandu","C":4},
{"id":211,"T":"E","P":"Blanco, blanca","R":"zuri|zuria","C":4},
{"id":212,"T":"E","P":"Bonito, bonita, guapo, guapa","R":"polit|polita","C":4},
{"id":213,"T":"E","P":"Bueno, buena","R":"on|ona","C":4},
{"id":214,"T":"E","P":"Cabezón, cabezona","R":"burugogor|burugogorra","C":4},
{"id":215,"T":"E","P":"Calentar","R":"berotu","C":4},
{"id":216,"T":"E","P":"Callado, callada","R":"isilik","C":4},
{"id":217,"T":"E","P":"Calvo, calva","R":"burusoil|burusoila","C":4},
{"id":218,"T":"E","P":"Cerrar","R":"itxi","C":4},
{"id":219,"T":"E","P":"Coche","R":"kotxe|kotxea","C":4},
{"id":220,"T":"E","P":"Coger","R":"hartu","C":4},
{"id":221,"T":"E","P":"Comer","R":"jan","C":4},
{"id":222,"T":"E","P":"Comprar","R":"erosi","C":4},
{"id":223,"T":"E","P":"Deberes","R":"etxerako lanak","C":4},
{"id":224,"T":"E","P":"Delgado, delgada","R":"argal|argala","C":4},
{"id":225,"T":"E","P":"Dormilón, dormilona","R":"loti|lotia","C":4},
{"id":226,"T":"E","P":"Encender","R":"piztu","C":4},
{"id":227,"T":"E","P":"Enfadar","R":"haserretu","C":4},
{"id":228,"T":"E","P":"Enfriar","R":"hoztu","C":4},
{"id":229,"T":"E","P":"Escribir","R":"idatzi","C":4},
{"id":230,"T":"E","P":"Escuchar","R":"entzun","C":4},
{"id":231,"T":"E","P":"Ese, esa, eso","R":"hori","C":4},
{"id":232,"T":"E","P":"Estar, haber","R":"egon","C":4},
{"id":233,"T":"E","P":"Feo, fea","R":"itsusi|itusia","C":4},
{"id":234,"T":"E","P":"Gordo, gorda","R":"lodi|lodia|potolo","C":4},
{"id":235,"T":"E","P":"Gris","R":"gris|grisa","C":4},
{"id":236,"T":"E","P":"Guardar","R":"gorde","C":4},
{"id":237,"T":"E","P":"Hablar","R":"hitz egin","C":4},
{"id":238,"T":"E","P":"Hacer","R":"egin","C":4},
{"id":239,"T":"E","P":"Ir","R":"joan","C":4},
{"id":240,"T":"E","P":"Leche","R":"esne|esnea","C":4},
{"id":241,"T":"E","P":"Leer","R":"irakurri","C":4},
{"id":242,"T":"E","P":"Limpiar","R":"garbitu","C":4},
{"id":243,"T":"E","P":"Llorar","R":"negar egin","C":4},
{"id":244,"T":"E","P":"Luz","R":"argi|argia","C":4},
{"id":245,"T":"E","P":"Malo, mala","R":"txar|txarra","C":4},
{"id":246,"T":"E","P":"Marrón","R":"marroi|marroia","C":4},
{"id":247,"T":"E","P":"Mesa","R":"mahai|mahaia","C":4},
{"id":248,"T":"E","P":"Meter","R":"sartu","C":4},
{"id":249,"T":"E","P":"Miedoso, miedosa","R":"beldurti|beldurtia","C":4},
{"id":250,"T":"E","P":"Naranja","R":"laranja","C":4},
{"id":251,"T":"E","P":"Negro, negra","R":"beltz|beltza","C":4},
{"id":252,"T":"E","P":"Conmigo","R":"nirekin","C":4},
{"id":253,"T":"E","P":"Oficina","R":"bulego|bulegoa","C":4},
{"id":254,"T":"E","P":"Precioso, preciosa","R":"eder|ederra","C":4},
{"id":255,"T":"E","P":"Puntual","R":"puntual|puntuala","C":4},
{"id":256,"T":"E","P":"Quieto, quieta","R":"geldi|geldia","C":4},
{"id":257,"T":"E","P":"Quitar","R":"kendu","C":4},
{"id":258,"T":"E","P":"Reir","R":"barre egin","C":4},
{"id":259,"T":"E","P":"Rojo, roja","R":"gorri|gorria","C":4},
{"id":260,"T":"E","P":"Rosa","R":"arrosa","C":4},
{"id":261,"T":"E","P":"Sacar","R":"atera","C":4},
{"id":262,"T":"E","P":"Salir","R":"irten","C":4},
{"id":263,"T":"E","P":"Saludar","R":"agur egin|agurtu","C":4},
{"id":264,"T":"E","P":"Secar","R":"lehartu","C":4},
{"id":265,"T":"E","P":"Sopa","R":"zopa","C":4},
{"id":266,"T":"E","P":"Subir","R":"igo","C":4},
{"id":267,"T":"E","P":"Televisión","R":"telebista","C":4},
{"id":268,"T":"E","P":"Tirar","R":"bota","C":4},
{"id":269,"T":"E","P":"Tocar","R":"ukitu","C":4},
{"id":270,"T":"E","P":"Triste","R":"triste","C":4},
{"id":271,"T":"E","P":"Vender","R":"saldu","C":4},
{"id":272,"T":"E","P":"Venir","R":"etorri","C":4},
{"id":273,"T":"E","P":"Verde","R":"berde|berdea","C":4},
{"id":274,"T":"E","P":"Vergonzoso, vergonzosa","R":"lotsati|lotsatia","C":4},
{"id":275,"T":"E","P":"Zapatos","R":"zapatak","C":4},
{"id":276,"T":"O","P":"Enciende la luz","R":"Piztu argia","C":4},
{"id":277,"T":"O","P":"Apaga la televisión","R":"Itzali telebista","C":4},
{"id":278,"T":"O","P":"Abre la puerta","R":"Ireki atea","C":4},
{"id":279,"T":"O","P":"Cierra la oficina","R":"Itxi bulegoa","C":4},
{"id":280,"T":"O","P":"Bebe la leche","R":"Edan esnea","C":4},
{"id":281,"T":"O","P":"Come la sopa","R":"Jan zopa","C":4},
{"id":282,"T":"O","P":"Haz los deberes","R":"Egin etxerako lanak","C":4},
{"id":283,"T":"O","P":"Calienta la cena","R":"Berotu afaria","C":4},
{"id":284,"T":"O","P":"Saca la basura","R":"Atera zarama","C":4},
{"id":285,"T":"O","P":"Guarda los zapatos","R":"Gorde zapatak","C":4},
{"id":286,"T":"O","P":"Pon la mesa","R":"Jarri mahaia","C":4},
{"id":287,"T":"O","P":"Tira la basura","R":"Bota zarama","C":4},
{"id":288,"T":"O","P":"Sube a casa","R":"Igo etxera","C":4},
{"id":289,"T":"O","P":"Baja a la calle","R":"Jaitsi kalera","C":4},
{"id":290,"T":"O","P":"Come el pan","R":"Jan ogia","C":4},
{"id":291,"T":"O","P":"Estate quieto y callado","R":"Egon geldi eta isilik","C":4},
{"id":292,"T":"O","P":"No toques eso","R":"Ez ukitu hori","C":4},
{"id":293,"T":"O","P":"No vengas tarde","R":"Ez etorri berandu","C":4},
{"id":294,"T":"O","P":"No te enfades conmigo","R":"Ez haserretu nirekin","C":4},
{"id":295,"T":"O","P":"Es la casa y la casa es verde","R":"Etxea da eta etxe verdea da","C":4},
{"id":296,"T":"O","P":"Es la bicicleta y la bicicleta es rosa","R":"Bizikleta da eta bizikleta arrosa da","C":4},
{"id":297,"T":"O","P":"Es el gato y el gato es gris","R":"Katua da eta katu grisa da","C":4},
{"id":298,"T":"O","P":"Es el automóvil y el automóvil es amarillo","R":"Automobila da eta automobil horia da","C":4},
{"id":299,"T":"O","P":"Es la puerta y la puerta es azul","R":"Atea da eta ate urdina da","C":4},
{"id":300,"T":"O","P":"Es la mesa y la mesa es negra","R":"Mahaia da eta mahai beltza da","C":4},
{"id":301,"T":"O","P":"Es la silla y la silla es morada","R":"Aulkia da eta aulki morea da","C":4},
{"id":302,"T":"O","P":"Es el zapato y el zapato es rojo","R":"Zapata da eta zapata gorria da","C":4},
{"id":303,"T":"O","P":"Es la modchila y la mochila es naranja","R":"Motzila da eta motxil laranja da","C":4},
{"id":304,"T":"O","P":"Es la casa y la casa es pequeña","R":"Etxea da eta etxea txikia da","C":4},
{"id":305,"T":"O","P":"Es la casa y la casa no es pequeña","R":"Etxea da eta etxe ez da txikia","C":4},
{"id":306,"T":"O","P":"Es el perro y el perro es pequeño","R":"Txakurra da eta txakur txikia da","C":4},
{"id":307,"T":"O","P":"Es el perro y el perro es grande","R":"Txakurra da eta txakur handia da","C":4},
{"id":308,"T":"O","P":"Es la fuente y la fuente es bonita","R":"Iturria da eta iturri polita da","C":4},
{"id":309,"T":"O","P":"Es la fuente y la fuente es grande","R":"Iturria da eta iturri handia da","C":4},
{"id":310,"T":"O","P":"Es el pato y el pato es joven","R":"Ahatea da eta ahate gaztea da","C":4},
{"id":311,"T":"O","P":"Es el pato y el pato es viejo","R":"Ahatea da eta ahate zaharra da","C":4}
]
